server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  rabbitmq:
    virtual-host: /xuecheng
    username: xuecheng
    password: xuecheng
    host: 192.168.1.104
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
   prefer‐ip‐address: true  #将自己的ip地址注册到Eureka服务中
   ip‐address: ${IP_ADDRESS:127.0.0.1}
   instance‐id: ${spring.application.name}:${server.port} #指定实例id