server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000
  rabbitmq:
    host: 192.168.1.104
    username: xuecheng
    password: xuecheng
    virtual-host: /xuecheng
    template:
      retry:
        enabled: true
        initial-interval: 10000s
        max-interval: 30000s
        multiplier: 2
      exchange: xuecheng.course.exchange
    publisher-confirms: true
mybatis:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
   prefer‐ip‐address: true  #将自己的ip地址注册到Eureka服务中
   ip‐address: ${IP_ADDRESS:127.0.0.1}
   instance‐id: ${spring.application.name}:${server.port} #指定实例id
course-publish:
  siteId: 5dd014f01588833c1cbb9192
  templateId: 5dd014a41588833c1cbb918d
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/
ribbon:
  eureka:
    enabled: true